spring.application.name=AutoScreenshotApplication
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/usersDb
spring.datasource.username=postgres
spring.datasource.password=19732846